### ISSUE TITLE
Favicon.ico reference not generated in pages when site builds

### ISSUE THREAD

**Issue by pypeaday** [WaylonWalker/markata#131]
I remember `favicon.ico` showing up sometime - not sure how to get that from the toml down into the rendered pages

**Comment by WaylonWalker** [comment]
I added a note in the (default blog starter](https://github.com/WaylonWalker/markata-blog-starter/blob/main/pages/your-own-style.md), which is probably the best starting guide I have.

Also added it to the theming page of the [docs](https://markata.dev/color-theme/#changing-your-favicon), both seem not the most discoverable.
