### ISSUE TITLE
Nav links in markata.toml should be affected by start_url

### ISSUE THREAD

**Issue by pypeaday** [WaylonWalker/markata#135]
If `start_url` is set in `markata.toml` and a nav link is set as `Home='/'`, what _should_ happen is the nav link is rendered to point to `/<start_url>`, but this doesn't currently happen in `markata~=0.6.0.dev0`  (this is what I set in CI - I will get a real version later)

**Comment by WaylonWalker** [comment]
sounds legit, I am going to do this for only links not containing `://` in case someone wants to hard link http:// https:// ftp:// ssh://

**Comment by WaylonWalker** [comment]
fixed in #136
