### ISSUE TITLE
Feature Request: Enable codeblock folding

### ISSUE THREAD

**Issue by pypeaday** [WaylonWalker/markata#137]
How hard would it be to enable an open/close on a code block, if say it's a particularly long one that you don't need to have take up all the screen real estate while reading a post?

Something kind of like https://github.com/bregman-arie/devops-exercises/blob/master/topics/devops/README.md where they have a question that expands into a long answer - but I have code blocks in mind more... 

thoughts?

**Comment by WaylonWalker** [comment]
Try this, thanks to the amazing facelessuser/pymdown-extensions https://facelessuser.github.io/pymdown-extensions/extensions/details/.

``` markdown
??? "the deets"
    more here

    ``` python
    import markata

    markata.run()
    ```
```
