### ISSUE TITLE
url typo

### ISSUE THREAD

**Issue by RensDimmendaal** [WaylonWalker/markata#15]
Hi Waylon,

I was just checking out your repo and noticed a typo where you link to the docs.

Good luck with the project!

![image](https://user-images.githubusercontent.com/9828683/152471252-a50d1a3a-f553-421f-b057-de7580a23711.png)

**Comment by WaylonWalker** [comment]
Thanks Very Much, fixed now!   Can't believe I can't even spell my own project name!
